### ISSUE TITLE
`claudia: command not found` error

### ISSUE THREAD

**Issue by edonosotti** [claudiajs/claudia-bot-builder#101]
With the latest version of `claudia` (`claudia-bot-builder@2.15.0`), both installing the package locally (`npm -S`) or globally (`npm -g`) the `claudia` script is missing and trying to run `claudia ...` commands raises the `claudia: command not found` error.

My `node` version is `v8.0.0`, `npm` in `5.3.0`, running on MacOSX.

**Comment by gojko** [comment]
check https://claudiajs.com/tutorials/installing.html for how to install claudia.

**Comment by karelhagel** [comment]
I'm having exactly the same problem: I followed the instructions in https://claudiajs.com/tutorials/installing.html and here's the result:
~/git/testdir: npm install claudia -g
/usr/local/Cellar/node/10.6.0/bin/claudia -> /usr/local/Cellar/node/10.6.0/lib/node_modules/claudia/bin/cmd.js
+ claudia@5.0.0
updated 2 packages in 4.042s
~/git/testdir: claudia --version
-bash: claudia: command not found
~/git/testdir:

**Comment by gojko** [comment]
@karelhagel this is not a problem with claudia. your node environment is not set up correctly, check your node and NPM installation to ensure that the NPM modules are added to your executable path

**Comment by karelhagel** [comment]
Thanks, I've added a link from my /usr/local/bin to the claudia library. It's now working.

**Comment by AimeurAmin** [comment]
@karelhagel  may you explain how you did that please.
