### ISSUE TITLE
"Build Failed" issue

### ISSUE THREAD

**Issue by Granddevv** [claudiajs/claudia-bot-builder#118]
Hi Claudia.

I used this package in my project for generating json data of FB templates.
It is running very well.

But during the build, I got this issue
"Failed to minify the code from this file: 

 	./node_modules/claudia-bot-builder/node_modules/souffleur/index.js:12 

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fb-messenger@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fb-messenger@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above."

Maybe it looks it is not pre-compiled to ES5.
How can I solve it?
Thanks.

**Comment by gojko** [comment]
This seems to be an issue with the souffleur package, not claudia bot builder, or with whatever you are using for minification. Please report it there.
