### ISSUE TITLE
Cannot add 'default_action' to Facebook generic template 

### ISSUE THREAD

**Issue by NiponChi** [claudiajs/claudia-bot-builder#119]
I would like to add default_action to Facebook generic template, like the code below.
```
    const generic = new fbTemplate.Generic();

    return generic
      .addBubble('Claudia.js', 'Deploy Node.js microservices to AWS easily')
        .addUrl('https://claudiajs.com')
        .addImage('https://claudiajs.com/assets/claudiajs.png')
        .addDefaultAction('https://github.com/claudiajs/claudia-bot-builder')
        .addButton('Say hello', 'HELLO')
        .addButton('Go to Github', 'https://github.com/claudiajs/claudia')
      .get()
```
---

* Expected behaviour:
Able to add `default_action` into generic template
https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic
* What actually happens:
There is no `addDefaultAction` method to add the action.
* Which bot engine (facebook, skype...): 
Facebook Messenger
* Link to a minimal, executable project that demonstrates the problem:
NA
* Steps to install the project:
NA
* Steps to reproduce the problem:
try the above snippet.

**Comment by stojanovic** [comment]
Would you like to try to send PR for this?

**Comment by stojanovic** [comment]
It's on NPM, version 4.2.0.
Can you just add this to [the documentation](https://github.com/claudiajs/claudia-bot-builder/blob/master/docs/FB_TEMPLATE_MESSAGE_BUILDER.md)?

Thanks again.

**Comment by stojanovic** [comment]
Thanks
