### ISSUE TITLE
How to implement delayed response? 

### ISSUE THREAD

**Issue by Montoya** [claudiajs/claudia-bot-builder#16]
I am building a bot that performs whois lookups for any domain the user provides. The whois lookup service can take a few seconds, and the limit for the server to respond to Slack is 3 seconds. Currently Claudia Bot Builder only allows me to return a string or JSON object to the request. I'm trying to figure out a way to take advantage of [delayed responses](https://api.slack.com/slash-commands#responding_to_a_command), so I can return a string right away and then POST a message to the Slack channel after the whois lookup completes. 

Here's a working example that shows I can post a delayed response as long as I do it before returning: 
(note: rp is the "request-promise" library and lookup is whois.lookup, promisified). 

```
return lookup(request.callback_id).then(function(data) {
	return rp({
		url: request.response_url,
		method: "POST",
		json: true,
		body: {
			'response_type':'in_channel',
			'replace_original':false,
			"attachments": [
        {
          "text": "```"+data+"```",
          "mrkdwn_in": ["text"]
        }
	    ]
		}
	}).then(function(body) {
		return {
			'response_type':'in_channel',
			'replace_original':false,
			"text":"OK"
		};
	});
}).catch(function(err) {
	return rp({
		url: request.response_url,
		method: "POST",
		json: true,
		body: {
			'response_type':'in_channel',
			'replace_original':false,
			"text":"WHOOPS"
		}
	}).then(function(body) {
		return {
			'response_type':'in_channel',
			'replace_original':false,
			"text":"WHOOPS"
		};
	});
});
```

Outcome: 
![screen shot 2016-07-05 at 2 50 36 pm](https://cloud.githubusercontent.com/assets/19909/16596003/e068be68-42bf-11e6-961c-95557ca839a7.png)

But this does not: 

```
lookup(request.callback_id).then(function(data) {
	console.log('we here!')
	rp({
		url: request.response_url,
		method: "POST",
		json: true,
		body: {
			'response_type':'in_channel',
			'replace_original':false,
			"attachments": [
        {
          "text": "```"+data+"```",
          "mrkdwn_in": ["text"]
        }
	    ]
		}
	});
}).catch(function(err) {
	rp({
		url: request.response_url,
		method: "POST",
		json: true,
		body: {
			'response_type':'in_channel',
			'replace_original':false,
			"text":"Sorry, an error occured: "+err
		}
	});
});;
return {
	'response_type':'in_channel',
	'replace_original':false,
	'text': 'Here is the info on file for *'+request.callback_id+'*:'
};
```

From what I can tell the lookup never executes 
(note there is no attachment)
![screen shot 2016-07-05 at 2 54 08 pm](https://cloud.githubusercontent.com/assets/19909/16596094/59f24f74-42c0-11e6-90a2-0fe3a8e20ce0.png)

Also the console.log message doesn't appear in my logs. 

Any help here? Is this not possible with Claudia Bot Builder?

**Comment by stojanovic** [comment]
Hey @Montoya,

At the moment the only way to do that is to send a post request immediately and delay the promise until you get the request later.
We are not supporting delayed requests out of the box because Lambda is not a server, and the default timeout for Lambda is 3 seconds.

But that's not a problem with your code. There are 3 problems I see here (and I hope this will explain why the first example works):

1. On line 1 you need to return lookup because otherwise it's not returning promise and Claudia is not waiting for it to finish. So it should be:

    ```js
    return lookup(request.callback_id).then(function(data) {
    ```

2. On line 3 you are again not returning promise so again Claudia would not wait for that before terminating the function. It should be:

    ```js
    return rp({
            url: request.response_url,
    ...
    ```

3. Last return is executed automatically and Claudia terminates Lambda function so it'll not wait for the second response at all since it'll not be executed before terminating the Lambda.

---

PS. Since you are building Slack bot with some formatting you might want to check out the Message builder for Slack: https://github.com/claudiajs/claudia-bot-builder/blob/master/docs/SLACK_MESSAGE_MESSAGE_BUILDER.md

**Comment by Montoya** [comment]
OK but if I add those returns then the whole thing won't work anyway... 

Is the solution here to make a request to a different lambda function that isn't built with Claudia for doing the whois lookup and posting the response when it is ready?

**Comment by stojanovic** [comment]
@Montoya yes, that or you can do something like this:

```js
return rp({
      method: 'POST',
      hostname: 'hooks.slack.com',
      port: 443,
      path: '/services/TXXXXXXXX/BXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX',
      headers: {
        'Content-type': 'application/json'
      },
      body: JSON.stringify({
        text: 'Immediate response'
      })
    }).then(() => new Promise((resolve, reject) => setTimeout(() => resolve('Delayed request'), 1000)))
```

It is not perfect but it works:
<img width="666" alt="delayed" src="https://cloud.githubusercontent.com/assets/613478/16598624/320d01c2-42ff-11e6-975a-e483c0dad31a.png">

**Comment by stojanovic** [comment]
Discard previous answer, you need to return something for the slash command so this will not work in this case.

**Comment by Montoya** [comment]
OK that last suggestion sounds like a great idea, I didn't realize that was even possible!

**Comment by Montoya** [comment]
Sorry to be obtuse, but would it be possible to get a simple example of this?

**Comment by gojko** [comment]
@stojanovic we can easily extend lambda runtime to be more than 3s (with `--timeout`). Perhaps we should add something to the slack api for delayed responses in the next version?

**Comment by stojanovic** [comment]
@Montoya yes, I'll send it a bit later.
@gojko I know that, but Slack requres an answer in 3s.

**Comment by gojko** [comment]
@stojanovic can we hold the HTTP connection for longer, and just do a delayed post if >3 sec after start, or would we have to decouple from the primary request?

**Comment by Montoya** [comment]
@gojko decoupling for the primary request would be the only way to go, because the issue with Slack is that when it makes a request, it waits for the response, effectively causing the Slack UI to hang... it's a terrible UX on Slack's part, but that's the reality. So if even if the request only takes 1 sec to complete, that's 1 second where the user will see either no response or even confirmation that their message was sent (for a Slash command) or a loading spinner (for a Message Button). 

It would be better, and probably the preferred approach, to return a simple HTTP 200 status code response, and always use delayed responses to post the reply, because then the UI would never hang for so long. Honestly at this point I'm kicking myself for using Claudia Bot Builder for this project without realizing this limitation (though I'll probably stick with Claudia since in every other respect, it's 100 times easier than any other bot framework I've tried, and this project is not so serious that I have to make it work perfectly).

**Comment by stojanovic** [comment]
@Montoya I started working on the example, but I have a bit packed day, expect it in the evening. It is easy to add one more API endpoint for additional requests, I just need 20 minutes of free time to finish the example :)

@gojko if you don't send an answer in 3s Slack will respond with a timeout message, they expect first return in <3s.

**Comment by Montoya** [comment]
@stojanovic No worries! Take as much time as you need :)

**Comment by gojko** [comment]
@stojanovic so I guess a systematic solution would be to allow a config arg to control if slack response is sync or async; in case of async we could just record all the req arguments, and do another lambda async invoke to itself, then immediately complete the http request. the bot builder could recognise the other request and actually execute the client function. there would be no code change to the client api, and we'd just know to do a delayed response in the second case. How does that sound?

**Comment by stojanovic** [comment]
@gojko sounds as a systematic solution (after second reading). Let's discuss that when you have some time.

@Montoya in the meantime this will work (I'll add it in the examples):

```js
'use strict'

const botBuilder = require('claudia-bot-builder')
const rp = require('minimal-request-promise')
const https = require('https')
const url = require('url')

// bot builder returns an API builder instance
const api = botBuilder((request, originalApiRequest) => {
  // Send a request to a new endpoint with a text and url in the params
  https.get(`https://${originalApiRequest.headers.Host}/${originalApiRequest.env.lambdaVersion}/delayed?text=${request.text}&url=${encodeURIComponent(request.originalRequest.response_url)}`, res => res.on('data', () => console.log('Done')))
    .on('error', e => console.error(e))

  // Wait 100ms to the request above to be sent and return instant response
  return new Promise((resolve, reject) => setTimeout(() => resolve('Immediate response'), 100))
})

// Add new method
api.get('/delayed', request => {
  // Parsing URL until we update minimal-request-promise (or use anything else)
  let options = url.parse(decodeURIComponent(request.queryString.url))
  options.method = 'POST'
  options.headers = { 'Content-Type': 'application/json' }
  options.body = JSON.stringify({ text: `Delayed response: ${request.queryString.text}` })

  // Wait 5s and make another Slack request
  return new Promise((resolve, reject) => setTimeout(() => resolve('ok'), 5000))
    .then(() => rp(options))
    .then(() => 'ok')
})

// Export an API builder instance in the end
module.exports = api
```

And it looks like this:
<img width="663" alt="screen shot 2016-07-06 at 22 09 33" src="https://cloud.githubusercontent.com/assets/613478/16632970/356fc3fe-43c7-11e6-9b53-b61da995b452.png">

**Comment by Montoya** [comment]
Thanks @stojanovic! I was able to get that to work but it's not consistent. Sometimes the delayed request doesn't fire until the next slash command request, for some reason. I think I'll wait for the more systematic approach.

**Comment by stojanovic** [comment]
Ok, I'll close this one and the real solution will be published probably in the next release.

**Comment by stojanovic** [comment]
@Montoya this is finally implemented, an example: https://github.com/claudiajs/example-projects/tree/master/slack-delayed-response

**Comment by Montoya** [comment]
Oh man that is so exciting! I can't wait to play with it tonight :)

**Comment by stojanovic** [comment]
Cool :)
Let us know if there's any other issue with that.
And send us the result, we want to make a list of the bots build with Claudia Bot Builder at some point ;)

**Comment by Montoya** [comment]
OK I kinda struggled with it all night because I tried setting up bot builder the way I normally would and then implementing the delayed response with the code example in the README and it just wouldn't work. So then I decided to start with the example files and follow the steps to install the dependencies and create the lambda function (and had to do an extra step `claudia update --configure-slack-slash-app` because some of the credentials weren't set up with the first create call) and guess what? It worked just fine! I think now I'll just modify the code sample to hook in my own functionality :) 

I think you might want to mention in the main claudia-bot-builder README that there are some slightly different setup commands for the delayed response slackbot because I just could not figure out how to get it working when I started with the main documentation steps. 

And I promise I will send you a link to the bot as soon as it gets approved by Facebook :)

**Comment by stojanovic** [comment]
@Montoya Cool! :)

Thanks for the suggestion. Where do you think we should add more explanation? In delayed reply docs?

Also, can you give me more details for this, sounds strange:
> and had to do an extra step claudia update --configure-slack-slash-app because some of the credentials weren't set up with the first create call

**Comment by Montoya** [comment]
I had to do the extra step because when I ran the install script it asked for my Slack token but didn't ask for my Slack Client ID or Secret. 

Will get back to you about the other question.

**Comment by stojanovic** [comment]
@Montoya ah that, that's ok, `--configure-slack-slash-command` is just a command for one team, not an app. We split that because it was a bit confusing to ask for client id and secret someone that doesn't need to provide it.

**Comment by gojko** [comment]
Here's a full tutorial how to run delayed responses with Slack https://claudiajs.com/tutorials/slack-delayed-responses.html
