### ISSUE TITLE
How to handle errors when replying? 

### ISSUE THREAD

**Issue by Montoya** [claudiajs/claudia-bot-builder#21]
I'm back again! The bot I'm building lets people search domain name availability. To test it, I tried "claudia" and one of the results is claudia.org. Unfortunately, it turns out that claudia.org is deemed an "unsafe URL" by Facebook, and any message containing that is automatically blocked by Facebook Messenger. The message (a big generic template message with 5 elements in the attachment) fails to send. Is there a way to handle errors when replying with Claudia Bot Builder? 

p.s. here's the error that gets logged when trying to send the message: 

```
{ headers:  { 'www-authenticate': 'OAuth "Facebook Platform" "invalid_request" "(#2022) Your message couldn\'t be sent because it includes content that other people on Facebook have reported as abusive."', 'access-control-allow-origin': '*', pragma: 'no-cache', 'cache-control': 'no-store', 'facebook-api-version': 'v2.6', expires: 'Sat, 01 Jan 2000 00:00:00 GMT', 'content-type': 'text/javascript; charset=UTF-8', 'x-fb-trace-id': 'A4qKNufqFlK', 'x-fb-rev': '2455931', vary: 'Accept-Encoding', 'x-fb-debug': 'IRzVg2dR09ZaEDhI++brtE7adsuTk1/Sp7p886mSobaK4tbS5iT/Xb4ex4yDhN7rtjSVDIuxAlST2+kc4HN7/Q==', date: 'Wed, 20 Jul 2016 16:54:24 GMT', connection: 'close', 'content-length': '208' }, body: '{"error":{"message":"(#2022) Your message couldn\'t be sent because it includes content that other people on Facebook have reported as abusive.","type":"OAuthException","code":2022,"fbtrace_id":"A4qKNufqFlK"}}', statusCode: 400, statusMessage: 'Bad Request' }
```

**Comment by gojko** [comment]
we don't have a mechanism for handling errors at the moment. if you have an idea what would be good to do about it, head over to the [claudia chat on gitter](https://gitter.im/claudiajs/claudia) to propose it.
