### ISSUE TITLE
InvalidClientTokenId: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by thierryskoda** [claudiajs/claudia-bot-builder#24]
*** Expected behaviour:**
Create the Facebook-messenger bot

*** What actually happens:**
After exectuting ```claudia create --region us-east-1 --api-module bot```. I've received the error 
```[InvalidClientTokenId: The security token included in the request is invalid.]```

*** Which bot engine (facebook, skype...):** 
Facebook

*** Link to a minimal, executable project that demonstrates the problem:**
https://github.com/thierryskoda/claudia-facebook-bot-example

*** Steps to install the project:**
npm install

*** Steps to reproduce the problem:**
execute ```claudia create --region us-east-1 --api-module bot```

***Screenshot**
<img width="602" alt="screen shot 2016-08-11 at 4 42 47 pm" src="https://cloud.githubusercontent.com/assets/6875849/17604191/b3034296-5fe2-11e6-895d-7849375bacd3.png">

**Comment by gojko** [comment]
does the AWS profile you run this under have access to IAM?

**Comment by thierryskoda** [comment]
Hum how can I know that? I'm really beginner with AWS

**Comment by gojko** [comment]
is the profile you are using for AWS a main account or a sub-account with restricted privileges? Check out https://claudiajs.com/tutorials/installing.html (the part about setting access credentials) to see where AWS SDK looks for profile info

**Comment by thierryskoda** [comment]
Oh Thank you very much!  It works right now. Those tutorials help a lot!
