### ISSUE TITLE
Web API Support

### ISSUE THREAD

**Issue by learnfunctionalprogramming** [claudiajs/claudia-bot-builder#37]
Hi.

I know this is not a bug, but here it goes:
Can this be used with a simple web API? I don't see it in the documentation.
As far as i can tell, it only works with Messenger, Skype, Telegram and Slack. Is there  way that can be used with a web API?
Also how could i use it with Serverless instead of Claudia? The main problem is that i can't do any real testing without lambda servers.

Thanks.

**Comment by gojko** [comment]
please use the gitter channel (https://gitter.im/claudiajs/claudia) for general questions. we use github issues only for bug reports
