### ISSUE TITLE
Thread Settings Reference

### ISSUE THREAD

**Issue by zampolli75** [claudiajs/claudia-bot-builder#47]
Hi,
I was trying to set a Welcome Message to my Bot. From the FB documentation it is stated that I should send a POST to https://graph.facebook.com/v2.6/**me/thread_settings**.

From what I can see looking through your code you only enable to the send POST to : https://graph.facebook.com/v2.6/**me/messages**.

Is there a way to send POST to 'me/thread_settings' with the current state of the code?

https://developers.facebook.com/docs/messenger-platform/thread-settings/greeting-text

Thank you.

**Comment by gojko** [comment]
Hi,
please use the gitter chat for general discussion (github.com/claudiajs/claudia), we use github issues for bugs only
