### ISSUE TITLE
Emoji prevents Viber messages

### ISSUE THREAD

**Issue by infojunkie** [claudiajs/claudia-bot-builder#57]
I followed the tutorial https://claudiajs.com/tutorials/viber-chatbot.html and it's working well. However, when the bot receives a string containing an emoji, such as 😀 , the reply never reaches Viber. I have checked that `request.text` (in `bot.js`) does contain the correct string, so it seems the reply gets lost inside the bot builder code itself. Also, I did verify that sending 😀 directly to the Viber API does result in a message.

**Comment by stojanovic** [comment]
Fixed in version 2.7.2

Thanks!
