### ISSUE TITLE
Typing Indicators

### ISSUE THREAD

**Issue by gilesbutler** [claudiajs/claudia-bot-builder#68]
Sorry for the general question guys but I can't get into your Gitter channel, it just won't load for me :(

I just want to know if it's possible to set the typing indicators whilst waiting for the bot to reply on Facebook?

I've searched everywhere before asking this and waited for 30 minutes to try and get into Gitter but no luck.

Thanks

**Comment by stojanovic** [comment]
@gilesbutler we don't have a template for typing for fb. At the moment you would need to send an object directly, and we'll add it to the templates at some point. Right now it exists only for Telegram as a part of a template builder library.

**Comment by gilesbutler** [comment]
Thanks @stojanovic - really appreciate the response! Am I write in thinking your [reply formats documentation](https://github.com/claudiajs/claudia-bot-builder/blob/master/docs/API.md#reply-formats) is what you are referring too when you say send an object directly? And then I presume it's a case of using the Facebook docs to send back the correct response?

**Comment by stojanovic** [comment]
`fbReply` function, that is invoked after returning the value from botBuilder, is wrapping text in an object expected from FB API or if you pass an object it is just adding that object as a message [here](https://github.com/claudiajs/claudia-bot-builder/blob/master/lib/facebook/reply.js#L16).

But it seems that we need to do a modification for typing, I'll try to do it today.

**Comment by gilesbutler** [comment]
Awesome! Thanks so much @stojanovic

**Comment by stojanovic** [comment]
Here it is: https://github.com/claudiajs/claudia-bot-builder/releases/tag/v2.10.0

**Comment by gilesbutler** [comment]
Thanks so much @stojanovic - incredible support 👍 really appreciate your help :)
