### ISSUE TITLE
support a debug mode

### ISSUE THREAD

**Issue by nbransby** [claudiajs/claudia-bot-builder#70]
where you catch exceptions and convert them to string and send them  as messages to user

save me doing:
```typescript
module.exports = builder(message, apiRequest) => {
    try {
      //bot code here
    } catch(error) {
        return String(error);
    }
})

**Comment by gojko** [comment]
Hi,

we use issues on github only for bugs. everything else should go to the [gitter channel](https://gitter.im/claudiajs/claudia). You're more than welcome to submit a PR if you like for this, but if you want to just ask for a new feature and chat about it, please do it on the chat.
