### ISSUE TITLE
support delays between messages when bot returns an array

### ISSUE THREAD

**Issue by nbransby** [claudiajs/claudia-bot-builder#71]
would be great if there was delay between each message when sending multiple - with typing indicator.

I guess to implement this on facebook you would have to listen out for the message echo and sent each message after receiving the previous message's echo?

**Comment by gojko** [comment]
Hi,

we use issues on github only for bugs. everything else should go to the [gitter channel](https://gitter.im/claudiajs/claudia). You're more than welcome to submit a PR if you like for this, but if you want to just ask for a new feature and chat about it, please do it on the chat.

**Comment by stojanovic** [comment]
This also already exists: https://github.com/claudiajs/claudia-bot-builder/blob/master/docs/FB_TEMPLATE_MESSAGE_BUILDER.md#pause-template
