### ISSUE TITLE
url in button postback caught by facebook

### ISSUE THREAD

**Issue by yipcma** [claudiajs/claudia-bot-builder#72]
* Expected behaviour: url mingled with other text sent as a string payload

* What actually happens: facbeook caught it as an invalid url

* Which bot engine (facebook, skype...): facebook

* Link to a minimal, executable project that demonstrates the problem: communicated with @stojanovic 

* Steps to install the project: N/A

* Steps to reproduce the problem: N/A

**Comment by stojanovic** [comment]
Fixed in v2.11.0, available on NPM.
Thanks
