### ISSUE TITLE
Failed to decrypt pairwise Id error with Skype bot

### ISSUE THREAD

**Issue by jrowen** [claudiajs/claudia-bot-builder#74]
I'm running into a 400 error: Failed to decrypt pairwise Id when trying to interact with a simple skype bot.  Could this be related to [recent authentication changes](https://docs.botframework.com/en-us/restapi/authentication#changes)?
```
'use strict'

const botBuilder = require('./lib/claudia-bot-builder')

module.exports = botBuilder(function (message, originalApiRequest) {
  return `I got ${message.text}`;
}, { platforms: ['skype'] });
```

**Comment by stojanovic** [comment]
It might be, we'll check, thanks for reporting.

**Comment by jrowen** [comment]
I think my original issue was because I was testing my bot via the bot framework web chat tool.  I don't see the error when testing via skype.

Is it possible to update the REST urls to support the complete bot framework?

I'm assuming the authentication urls will still need to be updated.

**Comment by simalexan** [comment]
@jrowen im on it, will be done before the end of the day. if its a hurry, feel free to notify

**Comment by simalexan** [comment]
@jrowen I've changed the authentication api urls for Skype in #79 
As previously mentioned, as a Skype bot it works, but as a Bot Framework Web Chat it does not work yet. Skype & Microsoft Web Chat are different platforms, will check them out later.
As Microsoft didn't have the online web chat emulator before and we didn't add its support, we haven't tried it before.
Will check the API difference for the web chat support

**Comment by stojanovic** [comment]
Let's close this since it's not affecting Skype directly. We'll see for web chat support, not sure if that's a priority, but PR is welcome.

**Comment by ryzam** [comment]
Hi guys, suddenly my bot running on azure is not working and the error message is "Failed to decrypt pairwise Id"

**Comment by stojanovic** [comment]
@ryzam Azure? Claudia Bot Builder works on AWS Lambda only, so I guess this is not a question related to it.

**Comment by ryzam** [comment]
@stojanovic sorry, i just google this issue when got an error message from my apps and redirected to this project.

**Comment by simalexan** [comment]
@ryzam not a problem. But while you're here, lets help out with what we know.
This is usually a problem that the ID of the conversation is not correct or the token authentication may be an issue. Focus on those two things.
