### ISSUE TITLE
Telegram addInlineKeyboard responses not working

### ISSUE THREAD

**Issue by IGZalejandrogonzalez** [claudiajs/claudia-bot-builder#77]
* Expected behaviour: When a user press a button in an inline keyboard (addInlineKeyboard) in a telegram bot, the server should receive the button 'callback_data'

* What actually happens: The server receive a response, but the handler function is not executed

* Which bot engine (facebook, skype...): Telegram

* Link to a minimal, executable project that demonstrates the problem:

* Steps to install the project:

* Steps to reproduce the problem:

**Comment by stojanovic** [comment]
Fixed with #78.
