### ISSUE TITLE
Hello World Chat Bot Example On Site Not Working

### ISSUE THREAD

**Issue by tetreault** [claudiajs/claudia-bot-builder#82]
Hello, I went through these steps [here (Hello World Chat Bot)](https://claudiajs.com/tutorials/hello-world-chatbot.html) after going through [installing and configuring claudia](https://claudiajs.com/tutorials/installing.html). 

The example simply skips to the deployment step running `claudia create --region us-east-1 --api-module bot`. All that happens is the following error: `Lambda handler is missing. please specify with --handler`.

This is literally following the steps in your Hello World, so I'm rather perplexed. Is your documentation wrong? Is the example incomplete? Any assistance is appreciated, I really want to incorporate ClaudiaJS in a few client projects but this feels like a concerning start.

Node: v4.7.2
NPM: v4.1.2
Claudia: v2.6.0

**Comment by gojko** [comment]
Just tried reproducing this by copying/pasting code from the example page, and it seems to work, so the issue is somewhere else. Can you make sure there's no space between `--` and `api-module`, and that you've typed that correctly? if that still fails, can you please paste your package.json and bot.js here

**Comment by stojanovic** [comment]
And make sure your file is called bot.js, if the name is different, ie. chatbot.js then it should be `--api-module chatbot`

**Comment by tetreault** [comment]
Very prompt responses, thank you both @gojko @stojanovic ! I facepalmed hard when noticing my error you're right.
